coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%     # optional leniency for overall coverage
    patch:
      default:
        target: 80%       # match Sonar’s gate for new code
        threshold: 0%     # no slack on the patch (tweak if you want)
        informational: false


comment:
  layout: "header, diff, flags, components, footer"
  behavior: default
  require_changes: false

ignore:
  - "tests/*"
  - "examples/*"
  - "CloudFlare-Demo/*"
  - "setup.py"
  - "*/test_*.py"
