coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
    patch:
      default:
        target: auto
        threshold: 1%
        base: auto

comment:
  layout: "header, diff, flags, components, footer"
  behavior: default
  require_changes: false

ignore:
  - "tests/*"
  - "examples/*"
  - "CloudFlare-Demo/*"
  - "setup.py"
  - "*/test_*.py"
